install:
	npm ci

start:
	npm start

build:
	npm run build

fix:
	npx npx eslint --ext js,jsx --no-eslintrc --config .eslintrc.yml --fix .

lint:
	npx eslint --ext js,jsx --no-eslintrc --config .eslintrc.yml  .


